urls.py
from django.urls import path,include
from .views import index

from .views import login_view

from .views import *
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static


app_name = 'dashboard'

urlpatterns =[
   path('', index, name = 'AdminHome'),
   path('search', search),
   path('login/', login_view, name="login"),
   # path('register/', register_user, name="register"),
   path("logout/", logout_view, name="logout"),
  

  

   path('new_vendor/',NewVendorView.as_view(),name='NewVendor'), 
   path('vendor_requests/',VendorRequestView.as_view(),name='VendorRequest'), 
   # path('all_vendors/',AllVendorsView.as_view(),name='AllVendors'), 
   # path('vendor/<int:pk>/', DetailVendorView.as_view(), name='vendor_detail'),





   #for contact
   path('contact/',ContactUsView.as_view(),name='contact'), 
   

  # for template testing
   # path('test_view/',TestView.as_view(),name='NewTest'),

  




]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard/includes/footer.html
{% comment %} <footer class="footer"> {% endcomment %}
                {% comment %} <div class="row"> {% endcomment %}
                    {% comment %} <div class="col-12 col-sm-6 text-center text-sm-left">
                        <p>&copy; Copyright 2019. All rights reserved.</p>
                    </div>
                   <div class="col  col-sm-6 ml-sm-auto text-center text-sm-right">
                        <p><a target="_blank" href="https://www.templateshub.net">Templates Hub</a></p>
                    </div> {% endcomment %}
                {% comment %} </div> {% endcomment %}
            {% comment %} </footer> {% endcomment %}

templates/dashboard/includes/header.html
{% load static %}
<header class="app-header top-bar">
    <!-- begin navbar -->
    <nav class="navbar navbar-expand-md">

        <!-- begin navbar-header -->
        <div class="navbar-header d-flex align-items-center">
            <a href="javascript:void:(0)" class="mobile-toggle"><i class="ti ti-align-right"></i></a>
            <a class="navbar-brand" href="index.html">
                <p class="logo-desktop" style="font-size: xx-large;color: white;">Shaadi.<span style="color: tomato;">Com</span></p>
                <!-- <img src="assets/img/logo.png" class="img-fluid logo-desktop" alt="logo" /> -->
                <img src="{% static 'dashboard/assets/img/logo-icon.png' %}" class="img-fluid logo-mobile" alt="logo" />
            </a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="ti ti-align-left"></i>
                    </button>
        <!-- end navbar-header -->
        <!-- begin navigation -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="navigation d-flex">
                <ul class="navbar-nav nav-left">
                    <li class="nav-item">
                        <a href="javascript:void(0)" class="nav-link sidebar-toggle">
                            <i class="ti ti-align-right"></i>
                        </a>
                    </li>

                    <h4 style="margin-top: 8%;"><span style="color: #fe4c1c;"> Welcome </span>{{user.first_name}}
                    </h4>

                    <li class="nav-item full-screen d-none d-lg-block" id="btnFullscreen">
                        <a href="javascript:void(0)" class="nav-link expand">
                            <i class="icon-size-fullscreen"></i>
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav nav-right ml-auto">

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:void(0)" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fe fe-bell"></i>
                            <span class="notify">
                                                    <span class="blink"></span>
                            <span class="dot"></span>
                            </span>
                        </a>
                        <div class="dropdown-menu extended animated fadeIn" aria-labelledby="navbarDropdown">
                            <ul>
                                <li class="dropdown-header bg-gradient p-4 text-white text-left">Notifications
                                    <a href="#" class="float-right btn btn-square btn-inverse-light btn-xs m-0">
                                        <span class="font-13"> Clear all</span></a>
                                </li>
                                <li class="dropdown-body min-h-240 nicescroll">
                                    <ul class="scrollbar scroll_dark max-h-240">
                                        <li>
                                            <a href="javascript:void(0)">
                                                <div class="notification d-flex flex-row align-items-center">
                                                    <div class="notify-icon bg-img align-self-center">
                                                        <div class="bg-type bg-type-md">
                                                            <span>HY</span>
                                                        </div>
                                                    </div>
                                                    <div class="notify-message">
                                                        <p class="font-weight-bold">New registered user</p>
                                                        <small>Just now</small>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)">
                                                <div class="notification d-flex flex-row align-items-center">
                                                    <div class="notify-icon bg-img align-self-center">
                                                        <div class="bg-type bg-type-md bg-success">
                                                            <span>GM</span>
                                                        </div>
                                                    </div>
                                                    <div class="notify-message">
                                                        <p class="font-weight-bold">New invoice received</p>
                                                        <small>22 min</small>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)">
                                                <div class="notification d-flex flex-row align-items-center">
                                                    <div class="notify-icon bg-img align-self-center">
                                                        <div class="bg-type bg-type-md bg-danger">
                                                            <span>FR</span>
                                                        </div>
                                                    </div>
                                                    <div class="notify-message">
                                                        <p class="font-weight-bold">Server error report</p>
                                                        <small>7 min</small>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)">
                                                <div class="notification d-flex flex-row align-items-center">
                                                    <div class="notify-icon bg-img align-self-center">
                                                        <div class="bg-type bg-type-md bg-info">
                                                            <span>HT</span>
                                                        </div>
                                                    </div>
                                                    <div class="notify-message">
                                                        <p class="font-weight-bold">Database report</p>
                                                        <small>1 day</small>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)">
                                                <div class="notification d-flex flex-row align-items-center">
                                                    <div class="notify-icon bg-img align-self-center">
                                                        <div class="bg-type bg-type-md">
                                                            <span>DE</span>
                                                        </div>
                                                    </div>
                                                    <div class="notify-message">
                                                        <p class="font-weight-bold">Order confirmation</p>
                                                        <small>2 day</small>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="dropdown-footer">
                                    <a class="font-13" href="javascript:void(0)"> View All Notifications
                                                </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    {% block search %} {% endblock search %}
                    <li class="nav-item dropdown user-profile">
                        <a href="javascript:void(0)" class="nav-link dropdown-toggle " id="navbarDropdown4" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="{% static 'dashboard/assets/img/avtar/02.jpg' %}" alt="avtar-img">
                            <span class="bg-success user-status"></span>
                        </a>
                        <div class="dropdown-menu animated fadeIn" aria-labelledby="navbarDropdown">
                            <div class="bg-gradient px-4 py-3">
                                <div class="d-flex align-items-center justify-content-between">
                                    <div class="mr-1">
                                        {% if user.first_name %}

                                        <h4 class="text-white mb-0">{{ user.first_name }}</h4>
                                        {% else %}
                                        <h4 class="text-white mb-0">{{ user.phone }}</h4>

                                        {% endif %}
                                        <p class="text-white">{{ branch.EmailID }}</p>
                                    </div>
                                    <a href="{% url 'dashboard:logout' %}" class="text-white font-20 tooltip-wrapper" data-toggle="tooltip" data-placement="top" title="" data-original-title="Logout"> <i class="zmdi zmdi-power"></i></a>
                                </div>
                            </div>
                            <div class="p-4">
                                <a class="dropdown-item d-flex nav-link" href="/sbtadmin/branch_detail/{{ branch.id }}">
                                    <i class="fa fa-user pr-2 text-success"></i> Profile</a>

                                {% comment %} <a class="dropdown-item d-flex nav-link" href="{% url 'dashboard:branch_report' %}">
                                    <i class="fa fa-compass pr-2 text-warning"></i>Branch Report</a> {% endcomment %}

                                <a class="dropdown-item d-flex nav-link " href="{% url 'dashboard:contact' %}">
                                    <i class="fa fa-phone pr-2 text-warning"></i>Contact</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <!-- end navigation -->
    </nav>
    <!-- end navbar -->
</header>

templates/dashboard/includes/side_nav.html
<aside class="app-navbar">
                    <!-- begin sidebar-nav -->
                    <div class="sidebar-nav scrollbar scroll_light">
                        <ul class="metismenu " id="sidebarNav">
                            <li class="nav-static-title">Personal</li>
                            <li class="active">
                                <a href="{% url 'dashboard:AdminHome' %}" aria-expanded="false">
                                    <span class="nav-title">Dashboards</span>
                               </a>
                            </li>
                            {% if user.is_superuser %}
                            
                            {% comment %} <li><a class="has-arrow" href="javascript:void(0)" aria-expanded="false"><i class="nav-icon ti ti-calendar"></i><span class="nav-title">Branch</span></a>
                                <ul aria-expanded="false">
                                    <li> <a href="{% url 'dashboard:NewBranch' %}">New Branch </a> </li>
                                    <li> <a href="{% url 'dashboard:AllBranches' %}">View All Branches</a> </li>
                                </ul>
                            </li> {% endcomment %}
                            {% else %}
                            {% endif %}
                           
                            <li class="nav-static-title">User Roles</li>
                           
                         
                            
                            <li>
                                <a class="has-arrow" href="javascript:void(0)" aria-expanded="false"><i class="nav-icon ti ti-user"></i> <span class="nav-title">Vendors</span></a>
                                <ul aria-expanded="false">
                                    <li><a href="{% url 'dashboard:NewVendor' %}">New Vendor</a></li>
                                    <li><a href="#">View All Vendors</a></li>
                                    <li><a href="">Vendor Requests</a></li>

                                </ul>
                            </li>
                            {% if user.is_superuser %}
                            
                         
                            {% else %}
                            {% endif %}
                           
                        </ul>
                    </div>
                    <!-- end sidebar-nav -->
                </aside>